// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHd6vFwxznzIDnIB6gczxS8763pLFwqP8',
    appId: '1:658778419383:web:0201f03e43cfda55481d32',
    messagingSenderId: '658778419383',
    projectId: 'pi3-ca',
    authDomain: 'pi3-ca.firebaseapp.com',
    storageBucket: 'pi3-ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBag_H_SPs0dSGvNNOT3My6dabA9EKYw2s',
    appId: '1:658778419383:android:a7043829b43532a7481d32',
    messagingSenderId: '658778419383',
    projectId: 'pi3-ca',
    storageBucket: 'pi3-ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvvpoa5qNCHyG5dLeSvDJcC7SQqpKQCrA',
    appId: '1:658778419383:ios:7d3dc9689d361cea481d32',
    messagingSenderId: '658778419383',
    projectId: 'pi3-ca',
    storageBucket: 'pi3-ca.firebasestorage.app',
    iosBundleId: 'com.example.rpgMobile2026',
  );
}
